import click

@click.command()
@click.argument("filename")
@click.option("--lang", default="txt", help="The language to initialize the code for.")
@click.option("--t", default="Document",help="Title in case of an HTML file")
def codegen(filename, lang, t):
    """ Creates a file with basic codes. """
    language = "."+lang  # The extension
    filename = filename + language  # The filename
    code = ""  # contents of the file
    if lang == "html":
        code = html(t)
    elif lang == "java":
        code = java(filename)
    else:
        pass
    file = open(filename, 'w+')
    file.write(code)
    file.close()

def html(title):
    code = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
</head>
<body>
    
</body>
</html>
    """
    return code


def java(filename):
    class_name = filename.replace(".java", "")
    code =f"""/**
 *
 * These Codes are generated by codegen v2020.APR
 * 
*/
public class {class_name}{{
    // Attributes

    /**
     * Constructor
     *
    */
    public {class_name}(){{
        // This code runs on initialization
    }}

    public static void main(String[] args){{
        System.out.println("Hello Codegen!");
    }}
}}

"""
    return code
